name: InfoBoardReborn
main: com.pixar02.infoboard.InfoBoardReborn
version: 1.6.2
author: pixar02
website : bit.ly/InfoBoardReloaded
description: Show a scoreboard
depend: [PlaceholderAPI, Vault, WorldGuard]
softdepend: [ProtocolLib]

commands:
  InfoBoardReborn:
    usage: /<command> [args]
    description: The main command for this plugin
    aliases: [ibr, ib, iboard, infob, Infoboard]
    
permissions:
  ibr.*:
    default: op
    children:
      ibr.Set: true
      ibr.Toggle: true
      ibr.Reload: true
      ibr.View: true
      ibr.Create: true
  ibr.View:
    default: true
  ibr.Toggle:
    default: true
  